import apiClient from "./services.js";

// Generated by Gemini CLI
const emailServices = {
  send(data) {
    return apiClient.post("/email/send", data);
  },
  notifyDepartment(departmentId, managerName) {
    return apiClient.post("/email/notifyDepartment", { departmentId, managerName });
  },
};

export default emailServices;
