<script setup>
import { defineProps, defineEmits, ref, watch, shallowRef, computed, onMounted } from "vue";
import {onClickOutside} from "@vueuse/core";
import userServices from "../services/userServices"
import emailServices from "../services/emailServices" // Generated by Gemini CLI

const props = defineProps({
  passedUser: { type: Object, default: () => ({}) },
  isOpen: Boolean,
  selectedComponent: { type: String, default: 'ProfileModal' },
});

const emit = defineEmits(["modal-close"]);
const target = ref(null);
const user = ref([]);
const foundUser = ref([]);

//open window selectors
const hasChosen = ref(false); //need to be refs, because refs are reactive and normal variables are not
const exists = ref(false);
const doesNotExist = ref(false);

const Id = ref("");

const form = ref({
    email: "",
    firstName: "",
    lastName: "",
    phoneNumber: "",
    role: "",
});
const currentComponent = ref(props.selectedComponent);
const selectedSchedules = ref([]);
const selectedPositions = ref([]);
const selectedTags = ref([]);
const employeeId = ref("12345");
const employeePayRate = ref("8.75");
const commentData = ref("");

onClickOutside(target, (event) => { //had issues with this one, needed to ignore certain clicks
  const target = event?.target;
  if (!target) return;
  // keep popups open when interacting with v-select menu dropdown
  if (target.closest('.v-menu, .v-overlay, .v-list-item, .v-select')) //ignoring these clickable items
    return;
  emit('modal-close');
});

const studentExists = () => {
    //console.log(props.passedUser) 
    doesNotExist.value = false;
    exists.value = true; 
    hasChosen.value = true;
}

const studentDoesNotExist = () => {
    exists.value = false;
    doesNotExist.value = true; 
    hasChosen.value = true;
}

const menuItems = [ //same as Sam's sidebar, but for the user modal
  { name: 'Profile', component: 'ProfileModal' }, //are the componet pieces needed anymore?
  { name: 'Assignments', component: 'AssignmentsModal' },
  { name: 'Hourly Rate', component: 'HourlyRatesModal' },
  { name: 'Log Notes', component: 'LogNotesModal' },
  { name: 'Advanced', component: 'AdvancedModal' },
]

watch(() => props.selectedComponent, (value) => {
    if (value) currentComponent.value = value;
});

const changeModalContent = (item) => {
    //console.log("Changing modal content to:", item);
    if(item == 'ProfileModal' && props.isOpen)
    {
        putUser();
    }
    currentComponent.value = item;
};

async function putUser() {
    //console.log("foundUser: " + JSON.stringify(foundUser.value));
    if(foundUser.value.id != null)
    {
        try {
            //console.log("pushing user with ID:", foundUser.value.id);
            const response = await userServices.update(foundUser.value.id, {
                department_id: props.passedUser.department_id,
                fName: form.value.firstName,
                lName: form.value.lastName,
                email: form.value.email,
                role: form.value.role || "Employee",
                phone_num: form.value.phoneNumber,
                oc_id: employeeId.value,
                pay_rate: employeePayRate.value || "8.75",
                manager_notes:  commentData.value || "",
            });
            console.log("Response: ", response.data);
            console.log("user data: ", "id", foundUser.value.id, "department", props.passedUser.department_id, "fname", form.value.firstName, "lname", form.value.lastName, "email", form.value.email, "role", form.value.role || "Employee", "phone_num", form.value.phoneNumber, "oc_id", foundUser.value.oc_id, "pay_rate", employeePayRate.value || "8.75", "manager_notes", commentData.value || "");
            //emit('modal-close');
        } catch (error) {
            console.error("Error updating user:", error);
            console.log("user data: ", "id", foundUser.value.id, "department", props.passedUser.department_id, "fname", form.value.firstName, "lname", form.value.lastName, "email", form.value.email, "role", form.value.role || "Employee", "phone_num", form.value.phoneNumber, "oc_id", foundUser.value.oc_id, "pay_rate", employeePayRate.value || "8.75", "manager_notes", commentData.value || "");
        }
    }
    else
    {
        try {
            console.log("pushing user");
            //if(!newUser.fName || !newUser.lName || !newUser.email || !newUser.role || !newUser.phone_num || !newUser.oc_id || !newUser.pay_rate || !newUser.manager_notes)
            {
                //console.log("Missing required fields");
                //return;
            }
            const response = await userServices.create({
                department_id: props.passedUser.department_id,
                fName: form.value.firstName,
                lName: form.value.lastName,
                email: form.value.email,
                role: form.value.role || "Employee",
                phone_num: form.value.phoneNumber,
                oc_id: employeeId.value,
                pay_rate: employeePayRate.value || "8.75",
                manager_notes:  commentData.value || "",
            });
            console.log("User created successfully:", response.data);

            // Generated by Gemini CLI - Email notification when a manager adds a user
            if (form.value.email) {
                const managerName = props.passedUser ? `${props.passedUser.fName} ${props.passedUser.lName}` : "a manager";
                const emailData = {
                    to: form.value.email,
                    subject: "You've been added to the Work Schedule App",
                    text: `Hello ${form.value.firstName}, you have been added to the Work Schedule App by ${managerName}. You can now sign in with your Google account.`,
                    html: `<p>Hello ${form.value.firstName},</p><p>You have been added to the Work Schedule App by <b>${managerName}</b>.</p><p>You can now sign in with your Google account.</p>`
                };
                try {
                    await emailServices.send(emailData);
                    console.log("Welcome email sent to new user");
                } catch (emailError) {
                    console.error("Error sending welcome email:", emailError);
                }
            }

            emit('modal-close');
        } catch (error) {
            console.error("Error creating user:", error);
        }
    }
}

const roleItems = [
    { title: 'Employee', value: 'Employee' },
    { title: 'Manager', value: 'Manager' },
];

const scheduleItems = [
    { title: 'Schedule 1', route: '/schedule1' },
    { title: 'Schedule 2', route: '/schedule2' },
    { title: 'Schedule 3', route: '/schedule3' },
];

const positionItems = [
    { title: 'Position 1', route: '/position1' },
    { title: 'Position 2', route: '/position2' },
    { title: 'Position 3', route: '/position3' },
];

const tagItems = [
    { title: 'Tag 1', route: '/tag1' },
    { title: 'Tag 2', route: '/tag2' },
    { title: 'Tag 3', route: '/tag3' },
];

const submit = () => { //having this might prevent some issues, but it does nothing
    //console.log('Form submitted'); //profile screen add button triggers this
};

async function quickAdd() {
    //found the user, will need to go back in later and link it to the new schedule page, and add this result there
    await getUser(Id.value).then(() => {
        emit('modal-close'); //close the modal after adding the user
    });
    putUser(); 
}

async function addAndEdit() {
    await getUser(Id.value);

    //console.log("Found user:", foundUser.value);
    //console.log("Form before filling:", form.value); //working now

    form.value.firstName = foundUser.value.fName;
    form.value.lastName = foundUser.value.lName;
    form.value.email = foundUser.value.email;
    form.value.phoneNumber = foundUser.value.phone_num;
    form.value.role = "Employee"; //just automatically set them to employee, can be changed by the manager manually

    //console.log("Form after filling:", form.value);
    //console.log("id: ", Id.value);
    employeeId.value = Id.value;
    //console.log("employeePayRate: ", foundUser.value.pay_rate);
    employeePayRate.value = foundUser.value.pay_rate ?? "8.75";;
    //console.log("commentData: ", foundUser.value.manager_notes);
    commentData.value = foundUser.value.manager_notes ?? "";//at time of writing , manager notes has not been tested to dev, so work-around

    studentDoesNotExist(); //switch to the other modal screen, for editing
}

async function getUser(oc_id) {
    console.log("Getting user with ID:", oc_id);
    try {
        const response = await userServices.getOCid(oc_id);
        //console.log("User found successfully:", response.data);
        foundUser.value = response.data;
        //console.log("PassedUser: ", props.passedUser);
        foundUser.value.department_id = props.passedUser.department_id; //change the users department_id to match the managers
        //console.log("foundUser: ", foundUser.value);
    } catch (error) {
        console.error("Error adding user:", error);
    }
}

</script>

<template>
    <div v-if="isOpen" class="modal-popup" >
        <div ref="target"> <!-- target of the clicking outside to close function -->
            <div class="choose-modal-container" v-if="!hasChosen">
                <!-- beginning of OC student selector window -->
                <div id="chooseTopBar">
                    <p id="chooseTitle">Add User</p>
                    <div id="chooseHeader">
                        <button @click.stop="emit('modal-close')">X</button>
                    </div>
                </div>
                <p id="chooseQuestion">Has this user logged in before?</p>
                <div id="selectionContainer">
                    <button @click="studentExists()">Yes</button>
                    <button @click="studentDoesNotExist()">No</button>
                </div>
            </div>
            <!-- end of OC student selector window -->
            <!-- beginning oc OC student version -->
            <div class="choose-modal-container" v-if="exists">
                <div id="chooseTopBar">
                    <p id="chooseTitle">Add User</p>
                    <div id="chooseHeader">
                        <button @click.stop="emit('modal-close')">X</button>
                    </div>
                </div>
                <div id="idFormContainer">
                    <p> User ID: </p>
                    <input v-model="Id" id="idInput"/>
                </div>
                <div id="selectionContainer">
                    <button @click="quickAdd()">Quick Add</button>
                    <button @click="addAndEdit()">Add and Edit</button>
                </div>
            </div>
            <!-- end of OC student version -->
            <!-- beginning of non-OCstudent version -->
            <div class="modal-container" v-if="doesNotExist">
                <v-list nav id="userModalNav">
                    <v-list-item v-for="item in menuItems" :key="item.name" @click="changeModalContent(item.component)">
                        <template>
                            <v-icon :icon="item.icon" />
                        </template>
                        <v-list-item-title id="userModalOptions">
                            {{ item.name }}
                        </v-list-item-title>
                    </v-list-item>
                </v-list>
                <!-- beginning of screens -->
                <div id="addUserModalScreen"> 
                    <!-- profile content -->
                    <div v-if="currentComponent == 'ProfileModal'">
                        <div>
                            <div id="topBar">
                                <p id="title">Add User</p>
                                <div id="header">
                                    <button @click.stop="emit('modal-close')">X</button>
                                </div>
                            </div>
                            <hr id="pageBreakTop"/>
                            <form @submit.prevent="submit" id="formContainer">
                                <div id="formHolder">
                                    <div id="formDiv">
                                        <div class="field">
                                            <label>First Name</label>
                                            <input id="firstNameForm" type="text" v-model="form.firstName" />
                                        </div>
                                        <div class="field">
                                            <label>Last Name</label>
                                            <input id="lastNameForm" type="text" v-model="form.lastName" />
                                        </div>
                                        <div class="field">
                                            <label>Email</label>
                                            <input id="emailForm" type="email" v-model="form.email" />
                                        </div>
                                        <div class="field">
                                            <label>Phone Number</label>
                                            <input id="phoneNumberForm" type="text" v-model="form.phoneNumber" />
                                        </div>
                                        <div class="field">
                                            <p class="dropdown-title"> Role </p>
                                            <v-select v-model="form.role" :items="roleItems" item-title="title" item-value="title" class="dropdown" hide-details @click.stop></v-select>                                        </div>
                                    </div> <!-- will need to change later to the users google picture -->
                                    <img id="userModalImage" src=""/>
                                </div>
                                <hr id="pageBreakBottom"/>
                                <div id="buttonDiv">
                                    <button id="addUserButton" type="submit">Add User</button>
                                    <button id="continueButton" @click="changeModalContent('AssignmentsModal')"> Continue to Assignments </button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <!-- assignments content -->
                    <div v-if="currentComponent == 'AssignmentsModal'"> 
                        <div id="assignmentsTopBar">
                            <p id="title">Add User</p>
                            <div id="header">
                                <button @click.stop="emit('modal-close')">X</button>
                            </div>
                        </div>
                        <hr id="assignmentsPageBreakTop"/>
                        <form @submit.prevent="submit" id="formContainer"> 
                            <div id="assignmentsFormDiv">
                                <p class="dropdown-title"> Schedules </p>
                                <v-select v-model="selectedSchedules" :items="scheduleItems" item-title="title" item-value="title" label="Select Schedules" class="dropdown" hide-details @click.stop></v-select>
                                <p class="dropdown-title"> Positions </p>
                                <v-select v-model="selectedPositions" :items="positionItems" item-title="title" item-value="title" label="Select Positions" class="dropdown" hide-details @click.stop></v-select>
                                <p class="dropdown-title"> Tags </p>
                                <v-select v-model="selectedTags" :items="tagItems" item-title="title" item-value="title" label="Select Tags" class="dropdown" hide-details @click.stop></v-select><!-- hide details is require to remove a vue computed spacer -->
                            </div>
                        </form>
                        <hr id="assignmentsPageBreakBottom"/>
                        <div id="assignmentsButtonDiv">
                            <button id="addAssignmentsButton" type="submit">Add Assignments</button>
                            <button id="continueButton" @click="changeModalContent('HourlyRatesModal')"> Continue to Hourly Rates </button>
                        </div>
                    </div>
                    <!-- hourly rates content -->
                    <div v-if="currentComponent == 'HourlyRatesModal'"> 
                        <div id="topBar">
                            <p id="title">User Hourly Rates</p>
                            <div id="header">
                                <button @click.stop="emit('modal-close')">X</button>
                            </div>
                        </div>
                        <hr id="pageBreakTop"/>
                        <div id="advancedFormContainer">
                            <p> Pay Rate </p>
                            <input v-model="employeePayRate" id="advancedInput"/>
                        </div>
                        <hr id="advancedPageBreakBottom"/>
                        <div id="hourlyRatesButtonDiv">
                            <button id="hourlyRatesAddUserButton" type="submit">Add Hourly Rates</button>
                            <button id="hourlyRatesContinueButton" @click="changeModalContent('LogNotesModal')"> Continue to Log Notes </button>
                        </div>
                    </div>
                    <!-- log notes content -->
                    <div v-if="currentComponent == 'LogNotesModal'">
                        <div id="topBar">
                            <p id="title">User Log Notes</p>
                            <div id="header">
                                <button @click.stop="emit('modal-close')">X</button>
                            </div>
                        </div>
                        <v-textarea label="Comments" v-model="commentData"></v-textarea>

                        <div id="buttonDiv">
                            <button id="addUserButton" type="submit">Add Log Notes</button>
                            <button id="continueButton" @click="changeModalContent('AdvancedModal')"> Continue to Advanced </button>
                        </div>
                    </div>
                    <!-- advanced content -->
                    <div v-if="currentComponent == 'AdvancedModal'" id="AdvancedModal">
                        <div id="topBar">
                            <p id="title">User Advanced</p>
                            <div id="header">
                                <button @click.stop="emit('modal-close')">X</button>
                            </div>
                        </div>
                        <hr id="pageBreakTop"/>
                        <div id="advancedFormContainer">
                            <p> Employee ID </p>
                            <input v-model="employeeId" id="advancedInput"/>
                        </div>
                        <hr id="advancedPageBreakBottom"/>
                        <div id="advancedButtonDiv">
                            <button id="addUserButton" type="submit">Add Info</button>
                            <button id="continueButton" @click="changeModalContent('ProfileModal')"> Save </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<style scoped>
/*                        */
/* start of addUser modal */
/*                        */

.userModalImage
{
    width: 100px;
    height: 100px;
    margin-left: 15px;
    margin-top: 15px;
    border-radius: 50%;
    object-fit: cover;
}

.modal-popup /* this is the popup not the items in the popup */
{
    position: fixed;
    z-index: 990;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.5);
}

.modal-container /* this is the box holding the items in the popup */
{
    display: flex;
    width: 300px;
    margin: 150px auto;
    /*cant have padding or it will throw off the orientation of this modal*/
    background-color: #fff;
    border-radius: 2px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.25);
    min-width: 57vw;
    min-height: 60vh;
}

.addUserModalScreen
{
    padding: 16px;
    box-sizing: border-box;
}

#userModalImage
{
    width: 100%;
    height: 100%;
    margin-top: 1vh;
    margin-right: 2vw;
    margin-bottom: 1vh;
    object-fit: cover;
}

#formHolder
{
    display: flex;
    gap: 20px;
}

#userModalNav 
{
    min-width: 8vw;
    min-height: 60vh;
    height: 100%;
    background-color: rgb(76, 76, 76);
    color: white;
}

#topBar
{
    padding-left: 15px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding-top: 15px;
    padding-right: 23px;
}

#header
{
    text-align: center;
    z-index: 999;
    min-width: 30px;
    min-height: 30px;
    border-radius: 2px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.2);
    background-color: rgb(76, 76, 76);
    color: white;
}

#footer
{
    text-align: center;
    z-index: 999;
    min-width: 200px;
    min-height: 30px;
    border-radius: 2px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.2);
    margin-top: auto; /* pushes the footer to the bottom */
    background-color: rgb(76, 76, 76);
    color: white;
}

#userModalOptions
{
    border-bottom: 1px solid black;
}

/*                      */
/* end of addUser modal */
/*                      */ 

/*                              */
/* start of addUser choose page */
/*                              */  


.choose-modal-container 
{
    align-self: center;
    display: flex;
    flex-direction: column;
    width: min(90vw, 620px);
    min-height: 60vh;
    background: #fff;
    border-radius: 2px;
    box-shadow: 0 2px 8px rgba(0,0,0,.25);
    overflow: hidden;
    margin: 150px auto;
}

#chooseTopBar 
{
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 12px 16px;
    border-bottom: 1px solid #ddd;
}

#chooseTitle 
{
    margin: 0;
}

#chooseHeader button 
{
    width: 32px;
    height: 32px;
    border: none;
    background: #4c4c4c;
    color: white;
    border-radius: 4px;
    cursor: pointer;
}

#chooseQuestion 
{
    margin-top: 16vh !important;
    margin: 24px auto 0;
    text-align: center;
}

#selectionContainer 
{
    flex: 1;
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
    max-height: 5vh;
    gap: 14px;
}

#selectionContainer > button 
{
    width: clamp(80px, 25%, 120px);
    min-height: 20px;
    cursor: pointer;
    border: 2px solid black;
}

/*                              */
/* end of addUser choose screen */
/*                              */

/*                            */
/* start of addUser OCId page */
/*                            */   

#idFormContainer
{
    margin-top: 20vh;
    margin-bottom: 0;
    align-self: center;
    top: 50%;
    transform: translateY(-30%);

}

#idInput
{
    width: 100%;
    padding: 4px;
    font-size: 16px;
    outline: 2px solid #000;
    border-color: #000;
}

/*                            */
/* end of addUser OCId screen */
/*                            */

/*                      */
/* addUser profile page */
/*                      */    

#buttonDiv
{
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding-left: 30vw;
    padding-right: 15px;
}

#addUserButton
{
    padding: 1px;
    text-align: center;
    outline-width: 2px;
    outline-color: black;
    outline-style: solid;
    margin-right: 10px;
}

#formContainer 
{
    width: 100%;
    max-width: 50vw; /* needs to match the inner size of the popup */
    margin: 0 auto;
    box-sizing: border-box;
}

#pageBreakTop
{
    margin-left: 15px;
    margin-top: 20px;
    margin-bottom: 20px;
    margin-right: 15px;
}

#pageBreakBottom
{
    overflow-x: visible;
    margin-left: 15px;
    margin-bottom: 11.5px;
    margin-right: 15px;
}

#formDiv
{
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr)); /* this is new and exciting */
    gap: 12px;
    min-height: 40vh; /* needs all this restriction to make the form usable */
    max-height: 70vh;
    min-width: 35vw;
    max-width: 30vw;
    overflow-y: auto;
    /*box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.1); /* just for a visual spacing constraints */
}

#form
{   
    padding-left: 1vw;
    padding-right: 1vw;
    min-height: 10vh;
    display: flex;
    flex-direction: column;
    gap: 10px;
}

#firstNameForm, #lastNameForm, #emailForm, #phoneNumberForm, #roleForm
{
    
    padding: 5px;
    font-size: 16px;
    outline-width: 2px;
    outline-color: black;
    outline-style: solid;
}

.field 
{
    padding-left: 15px;
    padding-right: 15px;
    display: flex;
    flex-direction: column;
}

/*                             */
/* end of addUser profile page */
/*                             */ 

/*                                    */
/* start of addUser hourly rates page */
/*                                    */ 

#hourlyRatesButtonDiv
{
    display: flex;
    align-items: center;
    padding-left: 28vw;
    padding-right: 15px;
    margin-bottom: auto !important;
}

#hourlyRatesContinueButton 
{
    background-color: rgb(76, 76, 76);
    color: white;
    min-width: 150px;
    outline: 2px solid black;
    min-width: 5vw;
}

#hourlyRatesAddUserButton
{
    padding: 1px;
    text-align: center;
    outline-width: 2px;
    outline-color: black;
    outline-style: solid;
    margin-right: 10px;
}

/*                                  */
/* end of addUser hourly rates page */
/*                                  */ 

/*                                   */
/* start of addUser Assignments page */
/*                                   */ 

#assignmentsTopBar
{
    padding-left: 15px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding-top: 15px;
}

#assignmentsFormDiv
{
    padding-left: 12px;
    display: flex;
    flex-direction: column;
    min-height: 40vh;
    max-height: 60vh;
    min-width: 47vw;
}

.dropdown
{
    width: 100%;
    box-sizing: border-box;
    background: #fff !important; /* override another background (I've lost track of which one) */
    border: none !important;
    border: 1px solid #ccc;
    border-radius: 4px;
    max-height: 200px;
}

.dropdown-menu:hover
{
    filter: brightness(60%); 
}

#assignmentsPageBreakTop
{
    margin-left: 15px;
    margin-top: 20px;
    margin-bottom: 10px;
    max-width: 47vw;
}

#assignmentsPageBreakBottom
{
    overflow-x: visible;
    margin-left: 15px;
    margin-bottom: 11.5px;
    max-width: 47vw;
}

#addAssignmentsButton
{
    text-align: center;
    outline-width: 2px;
    outline-color: black;
    outline-style: solid;
    min-width: 150px;
}

#assignmentsButtonDiv
{
    display: flex;
    justify-content: flex-end;
    align-items: center;
    gap: 10px;
    padding: 10px 15px;
    width: 100%;
    box-sizing: border-box;
}

#continueButton 
{
    background-color: rgb(76, 76, 76);
    color: white;
    min-width: 150px;
    outline: 2px solid black;
}

/*                                 */
/* end of addUser Assignments page */
/*                                 */ 

/*                                */
/* start of addUser Advanced page */
/*                                */ 

#advancedModal
{
    display: flex;
    width: 100%;
}

#advancedPageBreakBottom
{
    margin-left: 15px;
    margin-bottom: 11.5px;
    margin-right: 15px;
    margin-top: min(40vh, 33vh); /* dont know what the first number does but the second is min margin */
    min-width: 46vw;
}

#advancedButtonDiv
{
    display: flex;
    align-items: center;
    padding-left: 33vw;
    padding-right: 15px;
    margin-bottom: auto !important;
}

#advancedFormContainer
{
    margin-left: 15px !important;  /* something was keeping this from working */
    height: 100%;
    max-width: 50vw;
}

#advancedInput
{
    outline: 1px solid black;
}

#advancedInput:focus
{
    outline: 2px solid black;
}

/*                              */
/* end of addUser Advanced page */
/*                              */ 
</style>